from .checkpoint_custody import (
    CheckpointCompatibilityError,
    CheckpointConsistencyError,
    CheckpointContractBindingError,
    CheckpointCustodyError,
    CheckpointIntegrityError,
    CheckpointWriteResult,
    CheckpointCustodyDocuments,
    ResumeSlotTransform,
    checkpoint_slot_names,
    checkpoint_slot_specs,
    load_latest_checkpoint,
    load_checkpoint_custody_documents,
    load_checkpoint_latest_pointer_file,
    load_checkpoint_latest_pointer_json,
    load_checkpoint_transaction_manifest_file,
    load_checkpoint_transaction_manifest_json,
    run_contract_binding,
    structural_abi_fingerprint,
    write_checkpoint_transaction,
)
from .preparation import (
    DEFAULT_EXECUTION_PREPARATION_PROVIDER_REGISTRY,
    ExecutionPreparationError,
    ExecutionPreparationProvider,
    ExecutionPreparationProviderRegistry,
    ExecutionPreparationRegistration,
    ExecutionPreparationRequest,
    ExecutionPreparationResult,
    require_execution_preparation_provider,
)
from .diagnostics import (
    CheckpointTransactionDiagnostic,
    LearningRateDiagnostic,
    NativeExecutionProducerContext,
    NativeTrainingDiagnosticsInput,
    ScheduleContextDiagnostic,
    TrainingDiagnostics,
)
from feedbax.contracts.run_matrix import (
    AuthoredTrainingRow,
    RowLowererIdentity,
    TrainingRowLoweringResult,
    TrainingRowPlanningProvenance,
    TrainingRowProvenance,
)

try:
    from ..config.hyperparams import load_hps
    from .trainer import (
        SimpleTrainer,
        grad_wrap_simple_loss_func,
        training_step_for_abstract_loss,
    )
    from .executor import (
        DiagnosticsEmissionConflictError,
        ManifestEmissionConflictError,
        StreamingCheckpointStore,
        TrainingRunExecutionResult,
        TrainingRunExecutorError,
        execute_training_run_spec,
        load_training_run_spec,
    )
    from .optimizers import (
        OptimizerStateCompatibilityError,
        build_optimizer,
        learning_rate_at_step,
        learning_rate_schedule,
        validate_optimizer_state_for_spec,
    )
    from .spec_storage import (
        TrainingSpecStorageResult,
        emit_training_run_spec_storage,
        stamp_training_run_manifest_identities,
    )
    from .run_matrix import (
        TrainingRowLowerer,
        materialize_adapted_run_matrix,
    )
except ImportError:
    pass

__all__ = [
    "CheckpointCompatibilityError",
    "CheckpointConsistencyError",
    "CheckpointContractBindingError",
    "CheckpointCustodyError",
    "CheckpointIntegrityError",
    "CheckpointWriteResult",
    "CheckpointCustodyDocuments",
    "CheckpointTransactionDiagnostic",
    "DiagnosticsEmissionConflictError",
    "LearningRateDiagnostic",
    "NativeExecutionProducerContext",
    "NativeTrainingDiagnosticsInput",
    "ResumeSlotTransform",
    "SimpleTrainer",
    "StreamingCheckpointStore",
    "ScheduleContextDiagnostic",
    "TrainingDiagnostics",
    "ManifestEmissionConflictError",
    "OptimizerStateCompatibilityError",
    "TrainingRunExecutionResult",
    "TrainingSpecStorageResult",
    "AuthoredTrainingRow",
    "RowLowererIdentity",
    "TrainingRowLowerer",
    "TrainingRowLoweringResult",
    "TrainingRowPlanningProvenance",
    "TrainingRowProvenance",
    "TrainingRunExecutorError",
    "DEFAULT_EXECUTION_PREPARATION_PROVIDER_REGISTRY",
    "ExecutionPreparationError",
    "ExecutionPreparationProvider",
    "ExecutionPreparationProviderRegistry",
    "ExecutionPreparationRegistration",
    "ExecutionPreparationRequest",
    "ExecutionPreparationResult",
    "build_optimizer",
    "checkpoint_slot_names",
    "checkpoint_slot_specs",
    "execute_training_run_spec",
    "emit_training_run_spec_storage",
    "grad_wrap_simple_loss_func",
    "load_hps",
    "load_latest_checkpoint",
    "load_checkpoint_custody_documents",
    "load_checkpoint_latest_pointer_file",
    "load_checkpoint_latest_pointer_json",
    "load_checkpoint_transaction_manifest_file",
    "load_checkpoint_transaction_manifest_json",
    "load_training_run_spec",
    "learning_rate_at_step",
    "learning_rate_schedule",
    "materialize_adapted_run_matrix",
    "run_contract_binding",
    "require_execution_preparation_provider",
    "structural_abi_fingerprint",
    "stamp_training_run_manifest_identities",
    "training_step_for_abstract_loss",
    "validate_optimizer_state_for_spec",
    "write_checkpoint_transaction",
]
