"""Graph execution runtime primitives."""

from feedbax.runtime.affine_composer import (
    AFFINE_VALUE_COMPOSER_SCHEMA_VERSION,
    AffineValueComposer,
    affine_value_composer_output_prototype,
)
from feedbax.runtime.channel import Channel, ChannelSpec, ChannelState, toggle_channel_noise
from feedbax.runtime.components import (
    Constant,
    DeadZone,
    DelayLine,
    Demux,
    ElementwiseAffineModulator,
    Gain,
    GRU,
    LSTM,
    Linear,
    Multiply,
    Mux,
    Ramp,
    RateLimiter,
    Ravel,
    Saturation,
    Sine,
    Sum,
    Switch,
    NAMED_ACTIVATIONS,
    identity_activation,
    resolve_activation,
)
from feedbax.runtime.graph import (
    Component,
    Graph,
    GraphState,
    GraphTraceRequest,
    RolloutStepContext,
    RolloutStepHook,
    RolloutStepHookResult,
    Wire,
    init_state_from_component,
)
from feedbax.runtime.model import (
    AbstractModel,
    wrap_stateless_callable,
    wrap_stateless_keyless_callable,
)
from feedbax.runtime.selectors import Selection, select, tree_at
from feedbax.runtime.state import CartesianState, State, StateBounds, StateT, clip_state
from feedbax.runtime.state_indices import align_state_indices_like
from feedbax.runtime.task_bindings import (
    COMPONENT_PARAMETER_ROLE,
    TaskBindingExposure,
    TaskInputPlan,
    TaskParameterStateInitPlan,
    apply_task_parameter_state_inits,
    binding_spec_from_legacy_extra_inputs,
    expose_task_bindings,
    expose_task_inputs,
    task_data_temporality,
)

__all__ = [
    "AbstractModel",
    "AFFINE_VALUE_COMPOSER_SCHEMA_VERSION",
    "AffineValueComposer",
    "CartesianState",
    "Channel",
    "ChannelSpec",
    "ChannelState",
    "Component",
    "COMPONENT_PARAMETER_ROLE",
    "Constant",
    "DeadZone",
    "DelayLine",
    "Demux",
    "ElementwiseAffineModulator",
    "Gain",
    "GRU",
    "Graph",
    "GraphState",
    "GraphTraceRequest",
    "LSTM",
    "Linear",
    "Multiply",
    "Mux",
    "NAMED_ACTIVATIONS",
    "Ramp",
    "RateLimiter",
    "Ravel",
    "RolloutStepContext",
    "RolloutStepHook",
    "RolloutStepHookResult",
    "Saturation",
    "Selection",
    "Sine",
    "State",
    "StateBounds",
    "StateT",
    "Sum",
    "Switch",
    "TaskBindingExposure",
    "TaskInputPlan",
    "TaskParameterStateInitPlan",
    "Wire",
    "apply_task_parameter_state_inits",
    "align_state_indices_like",
    "affine_value_composer_output_prototype",
    "binding_spec_from_legacy_extra_inputs",
    "clip_state",
    "expose_task_bindings",
    "expose_task_inputs",
    "identity_activation",
    "init_state_from_component",
    "resolve_activation",
    "select",
    "task_data_temporality",
    "toggle_channel_noise",
    "tree_at",
    "wrap_stateless_callable",
    "wrap_stateless_keyless_callable",
]
