"""Portable Feedbax contract models.

This package owns shared Pydantic contracts that are consumed by core,
provider, worker, and web layers. Transport-specific API models should remain
under their transport package.
"""

from feedbax.contracts.component import ComponentDefinition, PortType, PortTypeSpec
from feedbax.contracts.graph import (
    AnalysisInputConsumerSpec,
    AnalysisInputRequirement,
    BarnacleSpec,
    ComponentSpec,
    GraphMetadata,
    GraphProject,
    GraphSpec,
    GraphUIState,
    NodeUIState,
    ParameterConstraintSpec,
    ParamSchema,
    ParamValue,
    RetainedObservableSpec,
    RetainedObservableTargetSpec,
    RetentionPolicySpec,
    StudioArtifactRef,
    StudioCollectionRef,
    StudioInterventionTransformSpec,
    StudioInterventionValueBounds,
    StudioManifestRef,
    StudioScenarioSpec,
    StudioSelectorRef,
    StudioStageSpec,
    StudioTaskBindingSpec,
    StudioValidationIssue,
    StudioValidationState,
    StudioWorkspaceSpec,
    TapSpec,
    TapTransform,
    UserPortSpec,
    ValidationError,
    ValidationResult,
    ValidationWarning,
    WireSpec,
)
from feedbax.contracts.training import (
    EarlyStoppingSpec,
    LossTermSpec,
    OptimizerSpec,
    TaskSpec,
    TimeAggregationSpec,
    TrainingConfig,
    TrainingSpec,
)
from feedbax.contracts.studio_api import (
    AnalysisJobStatusResponse,
    AnalysisPackagesResponse,
    ComponentListResponse,
    GenerateAnalysisResponse,
    GraphCreateResponse,
    GraphDetailResponse,
    GraphListResponse,
    SuccessResponse,
    TrainingStartResponse,
    TrainingStatusResponse,
    WorkerStatusEnvelope,
)

__all__ = [
    "AnalysisInputConsumerSpec",
    "AnalysisInputRequirement",
    "AnalysisJobStatusResponse",
    "AnalysisPackagesResponse",
    "BarnacleSpec",
    "ComponentDefinition",
    "ComponentListResponse",
    "ComponentSpec",
    "EarlyStoppingSpec",
    "GenerateAnalysisResponse",
    "GraphMetadata",
    "GraphProject",
    "GraphCreateResponse",
    "GraphDetailResponse",
    "GraphListResponse",
    "GraphSpec",
    "GraphUIState",
    "LossTermSpec",
    "NodeUIState",
    "OptimizerSpec",
    "ParameterConstraintSpec",
    "ParamSchema",
    "ParamValue",
    "PortType",
    "PortTypeSpec",
    "RetainedObservableSpec",
    "RetainedObservableTargetSpec",
    "RetentionPolicySpec",
    "StudioArtifactRef",
    "StudioCollectionRef",
    "StudioInterventionTransformSpec",
    "StudioInterventionValueBounds",
    "StudioManifestRef",
    "StudioScenarioSpec",
    "StudioSelectorRef",
    "StudioStageSpec",
    "StudioTaskBindingSpec",
    "StudioValidationIssue",
    "StudioValidationState",
    "StudioWorkspaceSpec",
    "SuccessResponse",
    "TapSpec",
    "TapTransform",
    "TaskSpec",
    "TimeAggregationSpec",
    "TrainingStartResponse",
    "TrainingStatusResponse",
    "TrainingConfig",
    "TrainingSpec",
    "UserPortSpec",
    "ValidationError",
    "ValidationResult",
    "ValidationWarning",
    "WorkerStatusEnvelope",
    "WireSpec",
]
