"""Single schema-identity authority for scientific compiler durable records."""

GRAPH_DOCUMENT_SCHEMA_ID = "feedbax.graph_document"
GRAPH_DOCUMENT_SCHEMA_VERSION = "1"
RESOLVED_GRAPH_SCHEMA_ID = "feedbax.resolved_graph"
RESOLVED_GRAPH_SCHEMA_VERSION = "2"
COMPILATION_RECORD_SCHEMA_ID = "feedbax.graph_compilation_record"
COMPILATION_RECORD_SCHEMA_VERSION = "3"
COMPILATION_FAILURE_SCHEMA_ID = "feedbax.graph_compilation_failure"
COMPILATION_FAILURE_SCHEMA_VERSION = "1"
EXPERIMENT_DOCUMENT_SCHEMA_ID = "feedbax.experiment_document"
EXPERIMENT_DOCUMENT_SCHEMA_VERSION = "1"
CAMPAIGN_DOCUMENT_SCHEMA_ID = "feedbax.campaign_document"
CAMPAIGN_DOCUMENT_SCHEMA_VERSION = "1"
RESOLVED_EXPERIMENT_SCHEMA_ID = "feedbax.resolved_experiment"
RESOLVED_EXPERIMENT_SCHEMA_VERSION = "1"
DECLARATION_DOCUMENT_SCHEMA_ID = "feedbax.declaration_document"
DECLARATION_DOCUMENT_SCHEMA_VERSION = "1"


__all__ = [
    "CAMPAIGN_DOCUMENT_SCHEMA_ID",
    "CAMPAIGN_DOCUMENT_SCHEMA_VERSION",
    "COMPILATION_FAILURE_SCHEMA_ID",
    "COMPILATION_FAILURE_SCHEMA_VERSION",
    "COMPILATION_RECORD_SCHEMA_ID",
    "COMPILATION_RECORD_SCHEMA_VERSION",
    "DECLARATION_DOCUMENT_SCHEMA_ID",
    "DECLARATION_DOCUMENT_SCHEMA_VERSION",
    "EXPERIMENT_DOCUMENT_SCHEMA_ID",
    "EXPERIMENT_DOCUMENT_SCHEMA_VERSION",
    "GRAPH_DOCUMENT_SCHEMA_ID",
    "GRAPH_DOCUMENT_SCHEMA_VERSION",
    "RESOLVED_EXPERIMENT_SCHEMA_ID",
    "RESOLVED_EXPERIMENT_SCHEMA_VERSION",
    "RESOLVED_GRAPH_SCHEMA_ID",
    "RESOLVED_GRAPH_SCHEMA_VERSION",
]
