"""Single schema-identity authority for scientific compiler durable records."""

GRAPH_DOCUMENT_SCHEMA_ID = "feedbax.graph_document"
GRAPH_DOCUMENT_SCHEMA_VERSION = "1"
RESOLVED_GRAPH_SCHEMA_ID = "feedbax.resolved_graph"
RESOLVED_GRAPH_SCHEMA_VERSION = "2"
COMPILATION_RECORD_SCHEMA_ID = "feedbax.graph_compilation_record"
COMPILATION_RECORD_SCHEMA_VERSION = "3"
COMPILATION_FAILURE_SCHEMA_ID = "feedbax.graph_compilation_failure"
COMPILATION_FAILURE_SCHEMA_VERSION = "1"


__all__ = [
    "COMPILATION_FAILURE_SCHEMA_ID",
    "COMPILATION_FAILURE_SCHEMA_VERSION",
    "COMPILATION_RECORD_SCHEMA_ID",
    "COMPILATION_RECORD_SCHEMA_VERSION",
    "GRAPH_DOCUMENT_SCHEMA_ID",
    "GRAPH_DOCUMENT_SCHEMA_VERSION",
    "RESOLVED_GRAPH_SCHEMA_ID",
    "RESOLVED_GRAPH_SCHEMA_VERSION",
]
