"""Public typed Feedbax plugin bootstrap interface, resolved on first use."""

from importlib import import_module


_PUBLIC_ATTR_MODULES = {
    "ANALYSIS_RECIPES": ".application",
    "APPLICATION_REGISTRY_KEYS": ".application",
    "ApplicationRegistryBundle": ".application",
    "COMPONENTS": ".application",
    "CONFORMANCE_CHECKS": ".application",
    "DRIVERS": ".application",
    "EVALUATION_BATCH_CONSUMERS": ".application",
    "EVALUATION_PRODUCT_UNION_FINALIZERS": ".application",
    "EVALUATION_RECIPES": ".application",
    "EXECUTION_PREPARATIONS": ".application",
    "EXPERIMENT_PACKAGES": ".application",
    "FIGURES": ".application",
    "REPORT_RECIPES": ".application",
    "ROW_LOWERERS": ".application",
    "TRAINING_METHODS": ".application",
    "new_registration_context": ".application",
    "BOOTSTRAP_CONTEXT_VERSION": ".bootstrap",
    "BootstrapError": ".bootstrap",
    "BootstrapErrorCode": ".bootstrap",
    "BootstrapState": ".bootstrap",
    "DOWNSTREAM_INTERFACE_POLICY_ID": ".bootstrap",
    "DOWNSTREAM_POLICY_EFFECTIVE_RELEASE": ".bootstrap",
    "DOWNSTREAM_PROTOCOL_CURRENT": ".bootstrap",
    "DOWNSTREAM_PROTOCOL_MINIMUM": ".bootstrap",
    "FamilyRequirement": ".bootstrap",
    "PLUGIN_DECLARATION_SCHEMA_ID": ".bootstrap",
    "PLUGIN_DECLARATION_SCHEMA_VERSION": ".bootstrap",
    "PLUGIN_DECLARATION_SCHEMA_VERSION_V1": ".bootstrap",
    "PLUGIN_PROTOCOL_VERSION": ".bootstrap",
    "PluginDeclaration": ".bootstrap",
    "PluginDependency": ".bootstrap",
    "PluginProvenance": ".bootstrap",
    "PluginRegistration": ".bootstrap",
    "RegistrationContext": ".bootstrap",
    "RegistryFamilyRegistration": ".bootstrap",
    "RegistryKey": ".bootstrap",
    "UnsupportedDownstreamProtocolVersion": ".bootstrap",
    "bootstrap_application": ".bootstrap",
    "discover_plugin_registrations": ".bootstrap",
    "validate_downstream_protocol_version": ".bootstrap",
    "ExperimentRegistry": ".registry",
    "ExperimentEnvelopeCompileRequest": "feedbax.contracts.experiment_envelope",
    "ExperimentEnvelopeCompileResult": "feedbax.contracts.experiment_envelope",
    "ExperimentEnvelopeRejection": "feedbax.contracts.experiment_envelope",
    "ExperimentEnvelopeRejectionCategory": "feedbax.contracts.experiment_envelope",
    "EvaluationAuthoringSchema": "feedbax.analysis.evaluation",
    "EvaluationBatchItem": "feedbax.analysis.evaluation",
    "EvaluationBatchRecipe": "feedbax.analysis.evaluation",
    "EvaluationBatchRowError": "feedbax.analysis.evaluation",
    "EvaluationRecipe": "feedbax.analysis.evaluation",
    "EvaluationRecipeRegistry": "feedbax.analysis.evaluation",
    "EvaluationRecipeResult": "feedbax.analysis.evaluation",
    "EvaluationBatchConsumer": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchConsumerInput": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchConsumerRegistry": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchFinalizeInput": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchFragment": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchMergeInput": "feedbax.analysis.evaluation_compaction",
    "EvaluationBatchMergeState": "feedbax.analysis.evaluation_compaction",
    "EvaluationCompactProductUnionFinalizerRegistry": "feedbax.analysis.evaluation_product_union",
    "EvaluationCompactProductUnionInput": "feedbax.analysis.evaluation_product_union",
    "AnalysisRecipe": "feedbax.analysis.specs",
    "AnalysisRecipeRegistry": "feedbax.analysis.specs",
    "AnalysisRecipeResult": "feedbax.analysis.specs",
    "EMPTY_STAGED_EXECUTION_CONTEXT": "feedbax.analysis.execution_context",
    "StagedExecutionContext": "feedbax.analysis.execution_context",
    "EvaluationStatesStructureProviderProtocol": "feedbax.analysis.validation",
    "TrainingMethodDescriptor": "feedbax.contracts.training",
    "TrainingMethodRegistry": "feedbax.contracts.training",
    "compile_training_method_authoring": "feedbax.training.authoring",
    "training_method_row_lowerer_registration": "feedbax.training.authoring",
    "ExecutionPreparationPlan": "feedbax.training.preparation",
    "ExecutionPreparationProvider": "feedbax.training.preparation",
    "ExecutionPreparationProviderRegistry": "feedbax.training.preparation",
    "ExecutionPreparationRegistration": "feedbax.training.preparation",
    "ExecutionPreparationRequest": "feedbax.training.preparation",
    "ExecutionPreparationResult": "feedbax.training.preparation",
    "TrainingRowLowererRegistration": "feedbax.training.row_lowering",
    "TrainingRowLowererRegistry": "feedbax.training.row_lowering",
    "TrainingRowLoweringContext": "feedbax.training.row_lowering",
    "TrainingRowLoweringResult": "feedbax.contracts.run_matrix",
}

# Submodules the eager facade used to bind as attributes of this package.
_PUBLIC_SUBMODULES = ("application", "bootstrap", "registry")

_NON_GUARANTEED_PLUGIN_EXPORTS = (
    "CONFORMANCE_CHECKS",
    "EXPERIMENT_PACKAGES",
    "FIGURES",
    "REPORT_RECIPES",
    "BOOTSTRAP_CONTEXT_VERSION",
    "ExperimentRegistry",
    "PLUGIN_DECLARATION_SCHEMA_ID",
    "PLUGIN_DECLARATION_SCHEMA_VERSION",
    "PLUGIN_DECLARATION_SCHEMA_VERSION_V1",
    "PLUGIN_PROTOCOL_VERSION",
    "ExperimentEnvelopeCompileRequest",
    "ExperimentEnvelopeCompileResult",
    "ExperimentEnvelopeRejection",
    "ExperimentEnvelopeRejectionCategory",
)

__all__ = [
    "DOWNSTREAM_INTERFACE_POLICY_ID",
    "DOWNSTREAM_PROTOCOL_CURRENT",
    "DOWNSTREAM_PROTOCOL_MINIMUM",
    "DOWNSTREAM_POLICY_EFFECTIVE_RELEASE",
    "UnsupportedDownstreamProtocolVersion",
    "validate_downstream_protocol_version",
    "BootstrapError",
    "BootstrapErrorCode",
    "BootstrapState",
    "FamilyRequirement",
    "PluginDeclaration",
    "PluginDependency",
    "PluginProvenance",
    "PluginRegistration",
    "RegistrationContext",
    "RegistryKey",
    "RegistryFamilyRegistration",
    "bootstrap_application",
    "discover_plugin_registrations",
    "new_registration_context",
    "DRIVERS",
    "APPLICATION_REGISTRY_KEYS",
    "ApplicationRegistryBundle",
    "COMPONENTS",
    "TRAINING_METHODS",
    "ROW_LOWERERS",
    "EXECUTION_PREPARATIONS",
    "ANALYSIS_RECIPES",
    "EVALUATION_RECIPES",
    "EVALUATION_BATCH_CONSUMERS",
    "EVALUATION_PRODUCT_UNION_FINALIZERS",
    "TrainingMethodDescriptor",
    "TrainingMethodRegistry",
    "TrainingRowLowererRegistration",
    "TrainingRowLowererRegistry",
    "TrainingRowLoweringContext",
    "TrainingRowLoweringResult",
    "ExecutionPreparationProvider",
    "ExecutionPreparationProviderRegistry",
    "ExecutionPreparationRegistration",
    "ExecutionPreparationRequest",
    "ExecutionPreparationResult",
    "ExecutionPreparationPlan",
    "compile_training_method_authoring",
    "training_method_row_lowerer_registration",
    "AnalysisRecipe",
    "AnalysisRecipeRegistry",
    "AnalysisRecipeResult",
    "EvaluationRecipe",
    "EvaluationRecipeRegistry",
    "EvaluationRecipeResult",
    "EvaluationBatchRecipe",
    "EvaluationAuthoringSchema",
    "EvaluationBatchItem",
    "EvaluationBatchRowError",
    "EvaluationStatesStructureProviderProtocol",
    "StagedExecutionContext",
    "EMPTY_STAGED_EXECUTION_CONTEXT",
    "EvaluationBatchConsumer",
    "EvaluationBatchConsumerRegistry",
    "EvaluationBatchConsumerInput",
    "EvaluationBatchMergeInput",
    "EvaluationBatchMergeState",
    "EvaluationBatchFinalizeInput",
    "EvaluationBatchFragment",
    "EvaluationCompactProductUnionFinalizerRegistry",
    "EvaluationCompactProductUnionInput",
    "CONFORMANCE_CHECKS",
    "EXPERIMENT_PACKAGES",
    "FIGURES",
    "REPORT_RECIPES",
    "BOOTSTRAP_CONTEXT_VERSION",
    "ExperimentRegistry",
    "PLUGIN_DECLARATION_SCHEMA_ID",
    "PLUGIN_DECLARATION_SCHEMA_VERSION",
    "PLUGIN_DECLARATION_SCHEMA_VERSION_V1",
    "PLUGIN_PROTOCOL_VERSION",
    "ExperimentEnvelopeCompileRequest",
    "ExperimentEnvelopeCompileResult",
    "ExperimentEnvelopeRejection",
    "ExperimentEnvelopeRejectionCategory",
]


def __getattr__(name: str):
    if name in _PUBLIC_SUBMODULES:
        value = import_module(f".{name}", __name__)
    else:
        try:
            module_name = _PUBLIC_ATTR_MODULES[name]
        except KeyError as exc:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
        value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__, *_PUBLIC_SUBMODULES})
