"""Run-orchestration support surfaces."""

from __future__ import annotations

import importlib

__all__ = [
    "EXECUTION_IDENTITY_ENVELOPE_SCHEMA_ID",
    "EXECUTION_IDENTITY_ENVELOPE_SCHEMA_VERSION",
    "EXECUTION_IDENTITY_ENVELOPE_SCHEMA_VERSION_V1",
    "CHECKPOINT_CUSTODY_ARCHIVE_FORMAT_ID",
    "CHECKPOINT_CUSTODY_ARCHIVE_FORMAT_VERSION",
    "CHECKPOINT_CUSTODY_ARCHIVE_MEDIA_TYPE",
    "CHECKPOINT_CUSTODY_ARCHIVE_MATERIALIZER_ID",
    "CHECKPOINT_CUSTODY_ARCHIVE_MATERIALIZER_VERSION",
    "RUN_ASSEMBLY_REQUEST_SCHEMA_ID",
    "RUN_ASSEMBLY_REQUEST_SCHEMA_VERSION",
    "RUN_ASSEMBLY_REQUEST_SCHEMA_VERSION_V1",
    "RUN_ASSEMBLY_REQUEST_SCHEMA_VERSION_V2",
    "RUN_ASSEMBLY_REQUEST_SCHEMA_VERSION_V3",
    "RUN_BUNDLE_SCHEMA_ID",
    "RUN_BUNDLE_SCHEMA_VERSION",
    "RUN_BUNDLE_SCHEMA_VERSION_V1",
    "RUN_BUNDLE_SCHEMA_VERSION_V2",
    "RUN_BUNDLE_SCHEMA_VERSION_V3",
    "RUN_BUNDLE_SCHEMA_VERSION_V4",
    "RUN_BUNDLE_SCHEMA_VERSION_V5",
    "RUN_BUNDLE_SCHEMA_VERSION_V6",
    "RUN_BUNDLE_SCHEMA_VERSION_V7",
    "RUN_BUNDLE_SCHEMA_VERSION_V8",
    "STAGED_ROOT_CUSTODY_REF_PREFIX",
    "STAGED_ROOT_CUSTODY_SCHEMA_ID",
    "STAGED_ROOT_CUSTODY_SCHEMA_VERSION",
    "DEPLOYMENT_POLICY_SCHEMA_ID",
    "DEPLOYMENT_POLICY_SCHEMA_VERSION",
    "CHECK_STATUS_FAIL",
    "CHECK_STATUS_PASS",
    "CHECK_STATUS_SKIPPED",
    "RUN_CONFORMANCE_SCHEMA_ID",
    "RUN_CONFORMANCE_SCHEMA_VERSION",
    "RUN_CONFORMANCE_SCHEMA_VERSION_V1",
    "REALIZED_DEPLOYMENT_RECORD_SCHEMA_ID",
    "REALIZED_DEPLOYMENT_RECORD_SCHEMA_VERSION",
    "RUN_EVENT_SCHEMA_ID",
    "RUN_EVENT_SCHEMA_VERSION",
    "RUN_SET_STATE_SCHEMA_ID",
    "RUN_SET_STATE_SCHEMA_VERSION",
    "RUN_SET_STATE_SCHEMA_VERSION_V4",
    "BatchLineFormatError",
    "AssemblyCompilerRegistry",
    "AssemblyContext",
    "AssemblyInputDeclaration",
    "AuthorizedBatchStop",
    "AuthoredIntentRef",
    "BudgetPolicy",
    "CertificateRow",
    "CheckEntry",
    "CheckRegistry",
    "ConformanceRowArtifacts",
    "CompiledExecutionRow",
    "CompiledRowStorageResult",
    "CompiledRunSet",
    "CompilerIdentity",
    "DeploymentPolicy",
    "DeploymentResourceRequest",
    "DriverRowProbe",
    "EnvironmentDeclaration",
    "ExecutionCapsuleRef",
    "ExecutionIdentityEnvelope",
    "ImmutableInputDigest",
    "ImmutableInputIdentity",
    "CheckpointCustodyArchiveMaterializer",
    "ImmutableInputArtifactRef",
    "InputCustodySource",
    "InputFormatIdentity",
    "GovernedTrainingRowParentDeclaration",
    "LaunchPolicy",
    "LocalDriverError",
    "LocalOrchestrationDriver",
    "OrchestrationDriver",
    "PreflightCheckEntry",
    "ReconciledRunStatus",
    "RepoRevision",
    "RealizedDeploymentRecord",
    "ResolvedSnapshotRef",
    "ResolvedAssemblyInput",
    "MaterializedStagedRoot",
    "SealedStagedRoot",
    "StagedExecutionRootBindings",
    "StagedRootCustody",
    "StagedRootCustodyError",
    "StagedRootFileRecord",
    "StagedRootKind",
    "StagedRootSnapshotBinding",
    "StagedRootSourceBinding",
    "RowIdentities",
    "RowConformanceRuntimeInputs",
    "RowLaunchSpec",
    "RowState",
    "RunBundle",
    "RunConformanceCertificate",
    "RunEvent",
    "RunEventEmitter",
    "RunEventProtocolError",
    "RunEventReader",
    "RunRowSpec",
    "RunAssemblyRequest",
    "RunSetState",
    "RunSetStateStore",
    "STAGE_ORDER",
    "StageEngine",
    "StageState",
    "StateLockError",
    "SchemaArtifactRef",
    "assemble_run_bundle",
    "assert_certificate_allows_completed_registration",
    "build_core_check_registry",
    "build_default_check_registry",
    "build_default_assembly_registry",
    "MatrixAuthorityError",
    "build_training_run_matrix_authority",
    "compute_environment_fingerprint",
    "default_orchestration_root",
    "format_batch_line",
    "mint_run_set_id",
    "materialize_staged_root_snapshot",
    "preflight_staged_root_bindings",
    "seal_staged_root",
    "staged_execution_bindings_for_bundle",
    "staged_execution_root_bindings",
    "verify_staged_root_snapshot",
    "verify_staged_root_snapshot_binding",
    "persist_compiled_row",
    "run_authority_preflight_checks",
    "run_preflight_checks",
    "run_conformance_checks",
    "write_conformance_certificate",
]

_EXPORT_MODULES = (
    "feedbax.orchestration.matrix_authority",
    "feedbax.orchestration.bundle",
    "feedbax.orchestration.input_materialization",
    "feedbax.orchestration.staged_root_custody",
    "feedbax.orchestration.assembly",
    "feedbax.orchestration.conformance",
    "feedbax.orchestration.drivers.base",
    "feedbax.orchestration.drivers.local",
    "feedbax.orchestration.events",
    "feedbax.orchestration.stages",
    "feedbax.orchestration.state",
)


def __getattr__(name: str):
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    for module_name in _EXPORT_MODULES:
        module = importlib.import_module(module_name)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
