"""Run-orchestration support surfaces."""

from feedbax.orchestration.conformance import (
    CHECK_STATUS_FAIL,
    CHECK_STATUS_PASS,
    CHECK_STATUS_SKIPPED,
    RUN_CONFORMANCE_SCHEMA_ID,
    RUN_CONFORMANCE_SCHEMA_VERSION,
    CertificateRow,
    CheckEntry,
    CheckRegistry,
    ConformanceRowArtifacts,
    RunConformanceCertificate,
    assert_certificate_allows_completed_registration,
    build_core_check_registry,
    build_default_check_registry,
    run_conformance_checks,
    write_conformance_certificate,
)
from feedbax.orchestration.events import (
    RUN_EVENT_SCHEMA_ID,
    RUN_EVENT_SCHEMA_VERSION,
    BatchLineFormatError,
    ReconciledRunStatus,
    RunEvent,
    RunEventEmitter,
    RunEventProtocolError,
    RunEventReader,
    format_batch_line,
)

__all__ = [
    "CHECK_STATUS_FAIL",
    "CHECK_STATUS_PASS",
    "CHECK_STATUS_SKIPPED",
    "RUN_CONFORMANCE_SCHEMA_ID",
    "RUN_CONFORMANCE_SCHEMA_VERSION",
    "RUN_EVENT_SCHEMA_ID",
    "RUN_EVENT_SCHEMA_VERSION",
    "BatchLineFormatError",
    "CertificateRow",
    "CheckEntry",
    "CheckRegistry",
    "ConformanceRowArtifacts",
    "ReconciledRunStatus",
    "RunConformanceCertificate",
    "RunEvent",
    "RunEventEmitter",
    "RunEventProtocolError",
    "RunEventReader",
    "assert_certificate_allows_completed_registration",
    "build_core_check_registry",
    "build_default_check_registry",
    "format_batch_line",
    "run_conformance_checks",
    "write_conformance_certificate",
]
